INSERT INTO geolocations VALUES(NULL,'US','AL', 'Alabama');
INSERT INTO geolocations VALUES(NULL,'US','AK', 'Alaska');
INSERT INTO geolocations VALUES(NULL,'US','AZ', 'Arizona');
INSERT INTO geolocations VALUES(NULL,'US','AR', 'Arkansas');
INSERT INTO geolocations VALUES(NULL,'US','CA', 'California');
INSERT INTO geolocations VALUES(NULL,'US','CO', 'Colorado');
INSERT INTO geolocations VALUES(NULL,'US','CT', 'Connecticut');
INSERT INTO geolocations VALUES(NULL,'US','DE', 'Delaware');
INSERT INTO geolocations VALUES(NULL,'US','FL', 'Florida');
INSERT INTO geolocations VALUES(NULL,'US','GA', 'Georgia');
INSERT INTO geolocations VALUES(NULL,'US','HI', 'Hawaii');
INSERT INTO geolocations VALUES(NULL,'US','ID', 'Idaho');
INSERT INTO geolocations VALUES(NULL,'US','IL', 'Illinois');
INSERT INTO geolocations VALUES(NULL,'US','IN', 'Indiana');
INSERT INTO geolocations VALUES(NULL,'US','IA', 'Iowa');
INSERT INTO geolocations VALUES(NULL,'US','KS', 'Kansas');
INSERT INTO geolocations VALUES(NULL,'US','KY', 'Kentucky');
INSERT INTO geolocations VALUES(NULL,'US','LA', 'Louisiana');
INSERT INTO geolocations VALUES(NULL,'US','ME', 'Maine');
INSERT INTO geolocations VALUES(NULL,'US','MD', 'Maryland');
INSERT INTO geolocations VALUES(NULL,'US','MA', 'Massachusetts');
INSERT INTO geolocations VALUES(NULL,'US','MI', 'Michigan');
INSERT INTO geolocations VALUES(NULL,'US','MN', 'Minnesota');
INSERT INTO geolocations VALUES(NULL,'US','MS', 'Mississippi');
INSERT INTO geolocations VALUES(NULL,'US','MO', 'Missouri');
INSERT INTO geolocations VALUES(NULL,'US','MT', 'Montana');
INSERT INTO geolocations VALUES(NULL,'US','NE', 'Nebraska');
INSERT INTO geolocations VALUES(NULL,'US','NV', 'Nevada');
INSERT INTO geolocations VALUES(NULL,'US','NH', 'New Hampshire');
INSERT INTO geolocations VALUES(NULL,'US','NJ', 'New Jersey');
INSERT INTO geolocations VALUES(NULL,'US','NM', 'New Mexico');
INSERT INTO geolocations VALUES(NULL,'US','NY', 'New York');
INSERT INTO geolocations VALUES(NULL,'US','NC', 'North Carolina');
INSERT INTO geolocations VALUES(NULL,'US','ND', 'North Dakota ');
INSERT INTO geolocations VALUES(NULL,'US','OH', 'Ohio');
INSERT INTO geolocations VALUES(NULL,'US','OK', 'Oklahoma');
INSERT INTO geolocations VALUES(NULL,'US','OR', 'Oregon');
INSERT INTO geolocations VALUES(NULL,'US','PA', 'Pennsylvania');
INSERT INTO geolocations VALUES(NULL,'US','RI', 'Rhode Island');
INSERT INTO geolocations VALUES(NULL,'US','SC', 'South Carolina');
INSERT INTO geolocations VALUES(NULL,'US','SD', 'South Dakota');
INSERT INTO geolocations VALUES(NULL,'US','TN', 'Tennessee');
INSERT INTO geolocations VALUES(NULL,'US','TX', 'Texas');
INSERT INTO geolocations VALUES(NULL,'US','UT', 'Utah');
INSERT INTO geolocations VALUES(NULL,'US','VT', 'Vermont');
INSERT INTO geolocations VALUES(NULL,'US','VA', 'Virginia');
INSERT INTO geolocations VALUES(NULL,'US','WA', 'Washington');
INSERT INTO geolocations VALUES(NULL,'US','WV', 'West Virginia');
INSERT INTO geolocations VALUES(NULL,'US','WI', 'Wisconsin');
INSERT INTO geolocations VALUES(NULL,'US','WY', 'Wyoming');
INSERT INTO geolocations VALUES(NULL,'US','DC', 'District of Columbia');
INSERT INTO geolocations VALUES(NULL,'US','AS', 'American Samoa');
INSERT INTO geolocations VALUES(NULL,'US','GU', 'Guam');
INSERT INTO geolocations VALUES(NULL,'US','MP', 'Northern Mariana Islands');
INSERT INTO geolocations VALUES(NULL,'US','PR', 'Puerto Rico');